// apps/NextJS/app/(frontend)/komik/chapter/[chapterId]/page.tsx
'use client';

import React, { useEffect, useState } from 'react';
import useSWR from 'swr';
import Link from 'next/link';
import { BaseUrl } from '@/lib/url';
import { ChevronLeft, ChevronRight, BookOpen, AlertTriangle, Loader } from 'lucide-react';
import { ImageWithFallback } from '@/components/ImageWithFallback';
import { Skeleton } from '@/components/ui/skeleton';

interface ChapterDetail {
  title: string;
  prev_chapter_id: string;
  next_chapter_id: string;
  list_chapter: string;
  images: string[];
}

interface PageProps {
  params: Promise<{ chapterId: string }>;
}

const fetcher = (url: string) => fetch(url).then((res) => res.json());

export default function ChapterPage({ params }: PageProps) {
  const [resolvedParams, setResolvedParams] = useState<{ chapterId: string } | null>(null);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    params.then(setResolvedParams);
    setMounted(true);
  }, [params]);

  const { data: chapter, error, isLoading } = useSWR<ChapterDetail>(
    mounted && resolvedParams
      ? `${BaseUrl}/api/komik/chapter?chapter_url=${resolvedParams.chapterId}`
      : null,
    fetcher,
    {
      revalidateOnFocus: false,
      shouldRetryOnError: false,
    }
  );

  if (!mounted || !resolvedParams) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background dark:bg-dark">
        <Loader className="w-12 h-12 animate-spin text-purple-600" />
      </div>
    );
  }

  if (error) {
    return (
      <main className="min-h-screen p-6 bg-background dark:bg-dark flex items-center justify-center">
        <div className="max-w-md text-center">
          <div className="p-6 bg-red-100 dark:bg-red-900/30 rounded-2xl flex flex-col items-center gap-4">
            <AlertTriangle className="w-12 h-12 text-red-600 dark:text-red-400" />
            <h1 className="text-2xl font-bold text-red-800 dark:text-red-200">
              Gagal Memuat Chapter
            </h1>
            <p className="text-red-700 dark:text-red-300">
              Silakan coba kembali beberapa saat lagi
            </p>
          </div>
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen p-4 md:p-6 bg-background dark:bg-dark">
      {/* Navigation Top */}
      <div className="max-w-7xl mx-auto mb-6 space-y-4">
        <h1 className="text-2xl md:text-3xl font-bold text-center bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
          {chapter?.title || <Skeleton className="h-8 w-64 mx-auto" />}
        </h1>

        <div className='p-6'>
        <div className="flex flex-col md:flex-row gap-4 items-stretch">
          {/* Previous Button */}
          <div className="flex-1 flex justify-center md:justify-start">
            {chapter?.prev_chapter_id ? (
              <Link
                scroll
                href={`/komik/chapter/${chapter.prev_chapter_id}`}
                className="w-full md:w-auto flex items-center justify-center gap-2 px-6 py-2 bg-purple-100 dark:bg-purple-900/50 text-purple-600 dark:text-purple-400 rounded-lg hover:bg-purple-200 dark:hover:bg-purple-800 transition-colors"
              >
                <ChevronLeft className="w-5 h-5" />
                <span className="hidden sm:inline">Chapter Sebelumnya</span>
                <span className="sm:hidden">Sebelumnya</span>
              </Link>
            ) : (
              <div className="w-full md:w-auto px-6 py-2 opacity-50 cursor-not-allowed flex items-center justify-center">
                <ChevronLeft className="w-5 h-5" />
              </div>
            )}
          </div>

          {/* Center Button */}
          <div className="flex-1 flex justify-center">
            <Link
              href={`/komik/detail/${chapter?.list_chapter}`}
              className="w-full md:w-auto flex items-center justify-center gap-2 px-6 py-2 bg-zinc-100 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-300 rounded-lg hover:bg-zinc-200 dark:hover:bg-zinc-700 transition-colors"
            >
              <BookOpen className="w-5 h-5" />
              <span className="hidden sm:inline">Daftar Chapter</span>
              <span className="sm:hidden">Daftar</span>
            </Link>
          </div>

          {/* Next Button */}
          <div className="flex-1 flex justify-center md:justify-end">
            {chapter?.next_chapter_id ? (
              <Link
                scroll
                href={`/komik/chapter/${chapter.next_chapter_id}`}
                className="w-full md:w-auto flex items-center justify-center gap-2 px-6 py-2 bg-purple-100 dark:bg-purple-900/50 text-purple-600 dark:text-purple-400 rounded-lg hover:bg-purple-200 dark:hover:bg-purple-800 transition-colors"
              >
                <span className="hidden sm:inline">Chapter Selanjutnya</span>
                <span className="sm:hidden">Selanjutnya</span>
                <ChevronRight className="w-5 h-5" />
              </Link>
            ) : (
              <div className="w-full md:w-auto px-6 py-2 opacity-50 cursor-not-allowed flex items-center justify-center">
                <ChevronRight className="w-5 h-5" />
              </div>
            )}
          </div>
        </div>
      </div>
      </div>

      {/* Image Content */}
      <div className="max-w-4xl mx-auto space-y-4">
        {isLoading ? (
          Array.from({ length: 5 }).map((_, i) => (
            <div key={i} className="relative group w-full">
              <Skeleton className="w-full h-auto aspect-[700/1000] rounded-xl border border-zinc-200 dark:border-zinc-700" />
              <Skeleton className="absolute bottom-2 right-2 h-6 w-20 rounded-md" />
            </div>
          ))
        ) : (
          chapter?.images?.map((image, index) => (
            <div key={`${image}-${index}`} className="relative group">
              <ImageWithFallback
                imageUrl={image}
                index={index}
              // className="w-full h-auto rounded-xl shadow-lg border border-zinc-200 dark:border-zinc-700"
              />
              <div className="absolute bottom-2 right-2 bg-black/50 text-white px-3 py-1 rounded-md text-sm opacity-0 group-hover:opacity-100 transition-opacity">
                Halaman {index + 1}
              </div>
            </div>
          ))
        )}
      </div>

      {/* Navigation Bottom (Fixed) */}
      {/* <div className="fixed bottom-0 left-0 right-0 bg-background/95 dark:bg-dark/95 backdrop-blur border-t border-zinc-200 dark:border-zinc-800">
        <div className="max-w-7xl mx-auto p-4">
          <div className="flex justify-between items-center gap-4">
            <div className="flex-1 flex justify-start">
              {chapter?.prev_chapter_id && (
                <Link
                  scroll
                  href={`/komik/chapter/${chapter.prev_chapter_id}`}
                  className="flex items-center gap-2 text-sm px-4 py-2 bg-zinc-100 dark:bg-zinc-800 rounded-lg hover:bg-zinc-200 dark:hover:bg-zinc-700 transition-colors"
                >
                  <ChevronLeft className="w-4 h-4" />
                  Sebelumnya
                </Link>
              )}
            </div>

            <Link
              href={`/komik/detail/${chapter?.list_chapter}`}
              className="flex items-center gap-2 text-sm px-4 py-2 bg-zinc-100 dark:bg-zinc-800 rounded-lg hover:bg-zinc-200 dark:hover:bg-zinc-700 transition-colors"
            >
              <BookOpen className="w-4 h-4" />
            </Link>

            <div className="flex-1 flex justify-end">
              {chapter?.next_chapter_id && (
                <Link
                  scroll
                  href={`/komik/chapter/${chapter.next_chapter_id}`}
                  className="flex items-center gap-2 text-sm px-4 py-2 bg-zinc-100 dark:bg-zinc-800 rounded-lg hover:bg-zinc-200 dark:hover:bg-zinc-700 transition-colors"
                >
                  Selanjutnya
                  <ChevronRight className="w-4 h-4" />
                </Link>
              )}
            </div>
          </div>
        </div>
      </div> */}
      <div className='p-6'>
        <div className="flex flex-col md:flex-row gap-4 items-stretch">
          {/* Previous Button */}
          <div className="flex-1 flex justify-center md:justify-start">
            {chapter?.prev_chapter_id ? (
              <Link
                scroll
                href={`/komik/chapter/${chapter.prev_chapter_id}`}
                className="w-full md:w-auto flex items-center justify-center gap-2 px-6 py-2 bg-purple-100 dark:bg-purple-900/50 text-purple-600 dark:text-purple-400 rounded-lg hover:bg-purple-200 dark:hover:bg-purple-800 transition-colors"
              >
                <ChevronLeft className="w-5 h-5" />
                <span className="hidden sm:inline">Chapter Sebelumnya</span>
                <span className="sm:hidden">Sebelumnya</span>
              </Link>
            ) : (
              <div className="w-full md:w-auto px-6 py-2 opacity-50 cursor-not-allowed flex items-center justify-center">
                <ChevronLeft className="w-5 h-5" />
              </div>
            )}
          </div>

          {/* Center Button */}
          <div className="flex-1 flex justify-center">
            <Link
              href={`/komik/detail/${chapter?.list_chapter}`}
              className="w-full md:w-auto flex items-center justify-center gap-2 px-6 py-2 bg-zinc-100 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-300 rounded-lg hover:bg-zinc-200 dark:hover:bg-zinc-700 transition-colors"
            >
              <BookOpen className="w-5 h-5" />
              <span className="hidden sm:inline">Daftar Chapter</span>
              <span className="sm:hidden">Daftar</span>
            </Link>
          </div>

          {/* Next Button */}
          <div className="flex-1 flex justify-center md:justify-end">
            {chapter?.next_chapter_id ? (
              <Link
                scroll
                href={`/komik/chapter/${chapter.next_chapter_id}`}
                className="w-full md:w-auto flex items-center justify-center gap-2 px-6 py-2 bg-purple-100 dark:bg-purple-900/50 text-purple-600 dark:text-purple-400 rounded-lg hover:bg-purple-200 dark:hover:bg-purple-800 transition-colors"
              >
                <span className="hidden sm:inline">Chapter Selanjutnya</span>
                <span className="sm:hidden">Selanjutnya</span>
                <ChevronRight className="w-5 h-5" />
              </Link>
            ) : (
              <div className="w-full md:w-auto px-6 py-2 opacity-50 cursor-not-allowed flex items-center justify-center">
                <ChevronRight className="w-5 h-5" />
              </div>
            )}
          </div>
        </div>
      </div>
    </main>
  );
}

// apps/solidjs/src/routes/komik/chapter/[chapterId].tsx
import { Title } from '@solidjs/meta';
import { A, useParams } from '@solidjs/router';
import {
  createResource,
  For,
  Show,
  Suspense,
  createSignal,
  onMount,
  onCleanup,
} from 'solid-js';
import { Motion } from 'solid-motionone';
import { httpClient } from '~/lib/http-client';
import { CachedImage } from '~/components/CachedImage';

// Matches OpenAPI ChapterResponse -> ChapterData schema
interface ChapterData {
  title: string;
  next_chapter_id: string;
  prev_chapter_id: string;
  list_chapter: string;
  images: string[];
}

interface ChapterResponse {
  message: string;
  data: ChapterData;
}

async function fetchChapter(slug: string): Promise<ChapterResponse> {
  return httpClient.fetchJson<ChapterResponse>(
    `/api/komik/chapter?chapter_url=${encodeURIComponent(slug)}`,
  );
}

export default function KomikChapterPage() {
  const params = useParams();
  const [data] = createResource(() => params.chapterId, fetchChapter);
  const [showControls, setShowControls] = createSignal(true);
  const [currentPage, setCurrentPage] = createSignal(1);

  // Auto-hide controls after 3 seconds
  let hideTimeout: ReturnType<typeof setTimeout>;
  const resetHideTimer = () => {
    setShowControls(true);
    clearTimeout(hideTimeout);
    hideTimeout = setTimeout(() => setShowControls(false), 3000);
  };

  onMount(() => {
    resetHideTimer();
    const handleMove = () => resetHideTimer();
    window.addEventListener('mousemove', handleMove);
    window.addEventListener('touchstart', handleMove);
    onCleanup(() => {
      clearTimeout(hideTimeout);
      window.removeEventListener('mousemove', handleMove);
      window.removeEventListener('touchstart', handleMove);
    });
  });

  const handleScroll = (e: Event) => {
    const container = e.target as HTMLElement;
    const images = container.querySelectorAll('img');
    let page = 1;
    images.forEach((img, i) => {
      const rect = img.getBoundingClientRect();
      if (rect.top < window.innerHeight / 2) {
        page = i + 1;
      }
    });
    setCurrentPage(page);
  };

  return (
    <>
      <Title>{data()?.data.title || 'Chapter'} | Asepharyana</Title>
      <main class="min-h-screen bg-black text-white" onScroll={handleScroll}>
        <Suspense
          fallback={
            <div class="min-h-screen flex items-center justify-center bg-black">
              <div class="flex flex-col items-center gap-4">
                <div class="w-16 h-16 border-4 border-primary/30 border-t-primary rounded-full animate-spin" />
                <span class="text-white/60">Loading chapter...</span>
              </div>
            </div>
          }
        >
          <Show when={data()}>
            {(response) => (
              <>
                {/* Floating Header */}
                <Motion.div
                  initial={{ y: -100 }}
                  animate={{ y: showControls() ? 0 : -100 }}
                  transition={{ duration: 0.3 }}
                  class="fixed top-0 left-0 right-0 z-50"
                >
                  <div class="glass-subtle bg-black/80 backdrop-blur-xl border-b border-white/10">
                    <div class="max-w-4xl mx-auto px-4 py-3 flex items-center justify-between">
                      {/* Back + Title */}
                      <div class="flex items-center gap-3 flex-1 min-w-0">
                        <A
                          href={response().data.list_chapter || '/komik'}
                          class="p-2 rounded-lg bg-white/5 hover:bg-white/10 transition-colors"
                        >
                          <svg
                            class="w-5 h-5"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              stroke-width="2"
                              d="M15 19l-7-7 7-7"
                            />
                          </svg>
                        </A>
                        <h1 class="text-sm md:text-base font-medium truncate">
                          {response().data.title}
                        </h1>
                      </div>

                      {/* Page Indicator */}
                      <div class="px-3 py-1 rounded-full bg-white/10 text-sm">
                        {currentPage()} / {response().data.images?.length || 0}
                      </div>
                    </div>
                  </div>
                </Motion.div>

                {/* Navigation Controls */}
                <Motion.div
                  initial={{ y: 100 }}
                  animate={{ y: showControls() ? 0 : 100 }}
                  transition={{ duration: 0.3 }}
                  class="fixed bottom-0 left-0 right-0 z-50"
                >
                  <div class="glass-subtle bg-black/80 backdrop-blur-xl border-t border-white/10">
                    <div class="max-w-4xl mx-auto px-4 py-3 flex items-center justify-center gap-4">
                      <Show when={response().data.prev_chapter_id}>
                        <A
                          href={`/komik/chapter/${encodeURIComponent(response().data.prev_chapter_id)}`}
                          class="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white/10 hover:bg-white/20 transition-all duration-200 font-medium"
                        >
                          <svg
                            class="w-5 h-5"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              stroke-width="2"
                              d="M15 19l-7-7 7-7"
                            />
                          </svg>
                          <span class="hidden sm:inline">Previous</span>
                        </A>
                      </Show>

                      <div class="flex items-center gap-2 px-4 py-2 rounded-xl bg-primary/20 text-primary">
                        <svg
                          class="w-5 h-5"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                        >
                          <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            d="M4 6h16M4 10h16M4 14h16M4 18h16"
                          />
                        </svg>
                        <span class="font-medium">{currentPage()}</span>
                      </div>

                      <Show when={response().data.next_chapter_id}>
                        <A
                          href={`/komik/chapter/${encodeURIComponent(response().data.next_chapter_id)}`}
                          class="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-primary text-primary-foreground hover:bg-primary/90 transition-all duration-200 font-medium"
                        >
                          <span class="hidden sm:inline">Next</span>
                          <svg
                            class="w-5 h-5"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              stroke-width="2"
                              d="M9 5l7 7-7 7"
                            />
                          </svg>
                        </A>
                      </Show>
                    </div>
                  </div>
                </Motion.div>

                {/* Images Container */}
                <div class="max-w-4xl mx-auto pt-20 pb-24">
                  <For each={response().data.images}>
                    {(img, i) => (
                      <div class="relative w-full">
                        <CachedImage
                          src={img}
                          alt={`Page ${i() + 1}`}
                          class="w-full select-none"
                          fallbackClass="w-full aspect-[2/3] bg-zinc-900 animate-pulse flex items-center justify-center"
                          loading="lazy"
                        />
                        {/* Page Number Overlay */}
                        <div class="absolute bottom-4 right-4 px-3 py-1 rounded-full bg-black/60 text-white/80 text-xs backdrop-blur-sm">
                          {i() + 1}
                        </div>
                      </div>
                    )}
                  </For>
                </div>

                {/* End of Chapter */}
                <div class="max-w-4xl mx-auto px-4 pb-32">
                  <div class="glass-subtle bg-white/5 rounded-2xl p-8 text-center">
                    <div class="w-16 h-16 mx-auto mb-4 rounded-full bg-primary/20 flex items-center justify-center">
                      <svg
                        class="w-8 h-8 text-primary"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          stroke-width="2"
                          d="M5 13l4 4L19 7"
                        />
                      </svg>
                    </div>
                    <h3 class="text-xl font-bold mb-2">End of Chapter</h3>
                    <p class="text-white/60 mb-6">
                      You've reached the end of this chapter
                    </p>
                    <div class="flex justify-center gap-4 flex-wrap">
                      <Show when={response().data.prev_chapter_id}>
                        <A
                          href={`/komik/chapter/${encodeURIComponent(response().data.prev_chapter_id)}`}
                          class="px-6 py-3 rounded-xl bg-white/10 hover:bg-white/20 transition-colors"
                        >
                          ← Previous Chapter
                        </A>
                      </Show>
                      <Show when={response().data.next_chapter_id}>
                        <A
                          href={`/komik/chapter/${encodeURIComponent(response().data.next_chapter_id)}`}
                          class="px-6 py-3 rounded-xl bg-primary text-primary-foreground hover:bg-primary/90 transition-colors"
                        >
                          Next Chapter →
                        </A>
                      </Show>
                    </div>
                  </div>
                </div>
              </>
            )}
          </Show>
        </Suspense>
      </main>
    </>
  );
}
