// apps/NextJS/app/(frontend)/komik/detail/[komikId]/page.tsx
'use client';

import React, { useState, useEffect } from 'react';
import useSWR from 'swr';
import Image from 'next/image';
import { BackgroundGradient } from '@/components/background/background-gradient';
import CardA from '@/components/card/MediaCard';
import ButtonA from '@/components/button/ScrollButton';
import Loading from './loading';
import { useRouter } from 'next/navigation';
import { ArrowRightIcon, BookmarkIcon, BookOpenIcon, CalendarIcon, CircleDot, FileTextIcon, StarIcon, TypeIcon, UserIcon } from 'lucide-react';
export const dynamic = 'force-dynamic';


interface Chapter {
  chapter: string;
  chapter_id: string;
  date: string;
}

interface Recommendation {
  slug: string;
  title: string;
  image: string;
}

interface MangaData {
  title: string;
  alternativeTitle: string;
  score: string;
  image: string;
  type: string;
  status: string;
  releaseDate: string;
  author: string;
  description: string;
  totalChapter: string;
  updatedOn: string;
  genres: string[];
  chapters: Chapter[];
  recommendations: Recommendation[];
}

const fetcher = (url: string) => fetch(url).then((res) => res.json());

export default function DetailMangaPage({
  params,
}: {
  params: Promise<{ komikId: string }>;
}) {
  const [resolvedParams, setResolvedParams] = useState<{
    komikId: string;
  } | null>(null);
  const router = useRouter();
  useEffect(() => {
    params.then(setResolvedParams);
  }, [params]);

  const { data: manga, error } = useSWR<MangaData>(
    resolvedParams
      ? `/api/komik/detail?komik_id=${resolvedParams.komikId}`
      : null,
    fetcher
  );

  const [bookmarked, setBookmarked] = useState(false);

  useEffect(() => {
    if (resolvedParams && typeof window !== 'undefined') {
      const bookmarks = JSON.parse(
        localStorage.getItem('bookmarks-komik') || '[]'
      );
      setBookmarked(
        bookmarks.some(
          (item: { slug: string }) => item.slug === resolvedParams.komikId
        )
      );
    }
  }, [resolvedParams]);

  const handleBookmark = () => {
    if (!resolvedParams) return;

    let bookmarks = JSON.parse(localStorage.getItem('bookmarks-komik') || '[]');

    if (bookmarked) {
      bookmarks = bookmarks.filter(
        (item: { slug: string }) => item.slug !== resolvedParams.komikId
      );
    } else {
      bookmarks.push({
        slug: resolvedParams.komikId,
        title: manga?.title,
        poster: manga?.image,
      });
    }

    localStorage.setItem('bookmarks-komik', JSON.stringify(bookmarks));
    setBookmarked(!bookmarked);
  };

  if (error)
    return (
      <p className='text-red-500 text-center'>Failed to load manga data</p>
    );
  if (!manga || !resolvedParams) return <Loading />;

  return (
    <main className='p-4 md:p-8 bg-background dark:bg-dark min-h-screen'>
      <div className='max-w-6xl mx-auto bg-white dark:bg-dark-foreground rounded-3xl shadow-xl dark:shadow-lg dark:shadow-zinc-800'>
        <BackgroundGradient className='rounded-[24px] p-6 md:p-10 bg-white dark:bg-zinc-900'>
          <div className='flex flex-col md:flex-row items-center md:items-start gap-8'>
            {/* Manga Cover Section */}
            <div className='w-full md:w-1/3 flex flex-col gap-4'>
              <div className='relative group overflow-hidden rounded-2xl shadow-xl hover:shadow-2xl transition-shadow duration-300'>
                <Image
                  src={manga.image}
                  alt={manga.title}
                  width={400}
                  height={600}
                  className='object-cover w-full aspect-[2/3] transform transition-transform duration-300 hover:scale-105'
                  priority
                />
                <div className='absolute inset-0 bg-gradient-to-t from-black/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity'/>
              </div>
              
              <button
                onClick={handleBookmark}
                className={`flex items-center justify-center gap-2 px-6 py-3 rounded-full font-semibold transition-all duration-300 ${
                  bookmarked 
                    ? 'bg-red-500/90 hover:bg-red-600 text-white' 
                    : 'bg-blue-500/90 hover:bg-blue-600 text-white'
                }`}
              >
                <BookmarkIcon className='w-5 h-5' />
                {bookmarked ? 'Bookmarked' : 'Bookmark'}
              </button>
            </div>

            {/* Manga Details Section */}
            <div className='w-full md:w-2/3 space-y-6'>
              <h1 className='text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600 dark:from-blue-400 dark:to-purple-400'>
                {manga.title}
              </h1>

              {/* Metadata Grid */}
              <div className='grid grid-cols-2 md:grid-cols-3 gap-4 p-4 bg-zinc-50 dark:bg-zinc-800 rounded-xl'>
                {[
                  { label: 'Score', value: manga.score, icon: <StarIcon className="w-5 h-5 text-amber-500"/> },
                  { label: 'Type', value: manga.type, icon: <TypeIcon className="w-5 h-5 text-blue-500"/> },
                  { label: 'Status', value: manga.status, icon: <CircleDot className="w-5 h-5 text-green-500"/> },
                  { label: 'Released', value: manga.releaseDate, icon: <CalendarIcon className="w-5 h-5 text-red-500"/> },
                  { label: 'Author', value: manga.author, icon: <UserIcon className="w-5 h-5 text-purple-500"/> },
                ].map((detail) => (
                  <div key={detail.label} className='flex items-center gap-3'>
                    <span className='p-2 bg-white dark:bg-zinc-700 rounded-lg'>
                      {detail.icon}
                    </span>
                    <div>
                      <p className='text-sm text-zinc-500'>{detail.label}</p>
                      <p className='font-medium dark:text-zinc-200'>
                        {detail.value || 'N/A'}
                      </p>
                    </div>
                  </div>
                ))}
              </div>

              {/* Genres */}
                <div className='flex flex-wrap gap-2'>
                  {manga.genres?.map((genre, index) => (
                  <span 
                    key={index}
                    className='px-3 py-1 text-sm bg-blue-100 dark:bg-blue-900/50 text-blue-800 dark:text-blue-200 rounded-full'
                  >
                    {genre}
                  </span>
                  ))}
                </div>

              {/* Description */}
              <div className='prose dark:prose-invert max-w-none'>
                <h3 className='text-xl font-semibold mb-2 text-zinc-800 dark:text-zinc-100'>
                  Synopsis
                </h3>
                <p className='text-zinc-600 dark:text-zinc-300 leading-relaxed'>
                  {manga.description || 'No description available.'}
                </p>
              </div>

              {/* Chapters Section */}
              <div className='space-y-4'>
                <h2 className='text-2xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent'>
                  Chapters
                </h2>
                <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3'>
                  {manga.chapters?.length > 0 ? (
                    manga.chapters.map((chapter) => (
                      <ButtonA 
                        key={chapter.chapter_id}
                        onClick={() => router.push(`/komik/chapter/${chapter.chapter_id}`)}
                        className='group flex items-center justify-between p-4 bg-white dark:bg-zinc-800 rounded-xl hover:bg-zinc-50 dark:hover:bg-zinc-700 transition-colors shadow-sm'
                      >
                        <span className='font-medium text-zinc-700 dark:text-zinc-200'>
                          {chapter.chapter}
                        </span>
                        <ArrowRightIcon className='w-5 h-5 text-zinc-400 group-hover:text-blue-500 transition-colors'/>
                      </ButtonA>
                    ))
                  ) : (
                    <div className='col-span-full py-6 text-center text-zinc-500 dark:text-zinc-400'>
                      <FileTextIcon className='mx-auto h-12 w-12 mb-3'/>
                      No chapters available
                    </div>
                  )}
                </div>
              </div>

              {/* Recommendations Section */}
              <div className='space-y-4'>
                <h2 className='text-2xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent'>
                  You Might Also Like
                </h2>
                <div className='flex overflow-x-auto pb-4 gap-4 scrollbar-thin scrollbar-thumb-zinc-300 scrollbar-track-transparent dark:scrollbar-thumb-zinc-600'>
                  {manga.recommendations?.length > 0 ? (
                    manga.recommendations.map((recommendation) => (
                      <div 
                        key={recommendation.slug}
                        className='flex-shrink-0 w-48 md:w-56'
                      >
                        <CardA
                          title={recommendation.title}
                          imageUrl={recommendation.image}
                          linkUrl={`/komik/detail/${recommendation.slug}`}
                        />
                      </div>
                    ))
                  ) : (
                    <div className='w-full py-6 text-center text-zinc-500 dark:text-zinc-400'>
                      <BookOpenIcon className='mx-auto h-12 w-12 mb-3'/>
                      No recommendations available
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        </BackgroundGradient>
      </div>
    </main>
);
}

// apps/solidjs/src/routes/komik/detail/[komikId].tsx
import { Title } from "@solidjs/meta";
import { A, useParams } from "@solidjs/router";
import { createResource, For, Show, Suspense } from "solid-js";
import { Motion } from "solid-motionone";
import { httpClient } from "~/lib/http-client";
import { CachedImage } from "~/components/CachedImage";

// Matches OpenAPI DetailData schema
interface Chapter {
    chapter: string;
    date: string;
    chapter_id: string;
}

interface KomikDetail {
    title: string;
    poster: string;
    description: string;
    status: string;
    type: string;
    release_date: string;
    author: string;
    total_chapter: string;
    updated_on: string;
    genres: string[];
    chapters: Chapter[];
}

async function fetchKomikDetail(slug: string): Promise<KomikDetail> {
    return httpClient.fetchJson<KomikDetail>(`/api/komik/detail?komik_id=${encodeURIComponent(slug)}`);
}

export default function KomikDetailPage() {
    const params = useParams();
    const [data] = createResource(() => params.komikId, fetchKomikDetail);

    return (
        <>
            <Title>{data()?.title || "Komik Detail"} | Asepharyana</Title>
            <main class="min-h-screen bg-background text-foreground">
                <Suspense fallback={
                    <div class="p-4 md:p-8 max-w-6xl mx-auto">
                        <div class="glass-card rounded-2xl p-6 md:p-8">
                            <div class="flex flex-col md:flex-row gap-8">
                                <div class="w-full md:w-1/3 aspect-[3/4] rounded-xl shimmer" />
                                <div class="flex-1 space-y-4">
                                    <div class="h-10 w-3/4 shimmer rounded-lg" />
                                    <div class="h-6 w-1/2 shimmer rounded-lg" />
                                    <div class="h-32 shimmer rounded-lg" />
                                </div>
                            </div>
                        </div>
                    </div>
                }>
                    <Show when={data()}>
                        {(komik) => (
                            <Motion.div
                                initial={{ opacity: 0, y: 20 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ duration: 0.5 }}
                                class="p-4 md:p-8 max-w-6xl mx-auto"
                            >
                                {/* Hero Section with Backdrop */}
                                <div class="relative rounded-3xl overflow-hidden mb-8">
                                    {/* Backdrop Blur Image */}
                                    <div class="absolute inset-0 z-0">
                                        <CachedImage
                                            src={komik().poster}
                                            alt=""
                                            class="w-full h-full object-cover scale-110 blur-3xl opacity-30"
                                        />
                                        <div class="absolute inset-0 bg-gradient-to-t from-background via-background/80 to-transparent" />
                                    </div>

                                    {/* Content */}
                                    <div class="relative z-10 p-6 md:p-10">
                                        <div class="flex flex-col md:flex-row gap-8">
                                            {/* Poster */}
                                            <div class="w-full md:w-1/3 lg:w-1/4">
                                                <div class="relative group">
                                                    <CachedImage
                                                        src={komik().poster}
                                                        alt={komik().title}
                                                        class="w-full rounded-2xl shadow-2xl ring-1 ring-white/10 group-hover:ring-primary/50 transition-all duration-300"
                                                        fallbackClass="w-full aspect-[3/4] rounded-2xl shimmer"
                                                    />
                                                    {/* Type Badge */}
                                                    <div class="absolute -top-3 -right-3 px-4 py-2 rounded-full bg-primary text-primary-foreground font-bold shadow-lg glow-sm">
                                                        {komik().type}
                                                    </div>
                                                </div>
                                            </div>

                                            {/* Info */}
                                            <div class="flex-1 space-y-6">
                                                <div>
                                                    <h1 class="text-3xl md:text-4xl font-bold mb-2 gradient-text">
                                                        {komik().title}
                                                    </h1>
                                                    <p class="text-muted-foreground">by {komik().author}</p>
                                                </div>

                                                {/* Stats Grid */}
                                                <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
                                                    <div class="glass-subtle rounded-xl p-4 text-center">
                                                        <div class="text-muted-foreground text-sm mb-1">Status</div>
                                                        <div class="font-semibold text-primary">{komik().status}</div>
                                                    </div>
                                                    <div class="glass-subtle rounded-xl p-4 text-center">
                                                        <div class="text-muted-foreground text-sm mb-1">Type</div>
                                                        <div class="font-semibold">{komik().type}</div>
                                                    </div>
                                                    <div class="glass-subtle rounded-xl p-4 text-center">
                                                        <div class="text-muted-foreground text-sm mb-1">Chapters</div>
                                                        <div class="font-semibold">{komik().total_chapter}</div>
                                                    </div>
                                                    <div class="glass-subtle rounded-xl p-4 text-center">
                                                        <div class="text-muted-foreground text-sm mb-1">Updated</div>
                                                        <div class="font-semibold text-sm">{komik().updated_on || '-'}</div>
                                                    </div>
                                                </div>

                                                {/* Genres */}
                                                <div class="flex flex-wrap gap-2">
                                                    <For each={komik().genres}>
                                                        {(genre) => (
                                                            <span class="px-4 py-1.5 rounded-full bg-primary/10 text-primary text-sm font-medium hover:bg-primary/20 transition-colors cursor-default">
                                                                {genre}
                                                            </span>
                                                        )}
                                                    </For>
                                                </div>

                                                {/* Description */}
                                                <div class="glass-subtle rounded-xl p-5">
                                                    <h3 class="font-semibold text-lg mb-3 flex items-center gap-2">
                                                        <svg class="w-5 h-5 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                                        </svg>
                                                        Description
                                                    </h3>
                                                    <p class="text-muted-foreground leading-relaxed">{komik().description}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                {/* Chapters Section */}
                                <div class="glass-card rounded-2xl p-6 md:p-8">
                                    <div class="flex items-center justify-between mb-6">
                                        <h2 class="text-2xl font-bold flex items-center gap-3">
                                            <div class="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
                                                <svg class="w-5 h-5 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 10h16M4 14h16M4 18h16" />
                                                </svg>
                                            </div>
                                            Chapters
                                        </h2>
                                        <span class="text-muted-foreground text-sm">
                                            {komik().chapters?.length || 0} chapters
                                        </span>
                                    </div>

                                    <div class="space-y-2 max-h-[500px] overflow-y-auto pr-2 scrollbar-thin">
                                        <For each={komik().chapters}>
                                            {(ch, i) => (
                                                <A
                                                    href={`/komik/chapter/${encodeURIComponent(ch.chapter_id)}`}
                                                    class="flex justify-between items-center p-4 rounded-xl bg-secondary/50 border border-border/50 hover:border-primary/50 hover:bg-primary/5 transition-all duration-200 group hover-lift"
                                                >
                                                    <div class="flex items-center gap-4">
                                                        <span class="w-10 h-10 rounded-lg bg-primary/10 text-primary font-bold flex items-center justify-center text-sm group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                                                            {i() + 1}
                                                        </span>
                                                        <span class="font-medium group-hover:text-primary transition-colors">
                                                            {ch.chapter}
                                                        </span>
                                                    </div>
                                                    <div class="flex items-center gap-3">
                                                        <span class="text-sm text-muted-foreground">{ch.date}</span>
                                                        <svg class="w-5 h-5 text-muted-foreground group-hover:text-primary group-hover:translate-x-1 transition-all" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                                                        </svg>
                                                    </div>
                                                </A>
                                            )}
                                        </For>
                                    </div>
                                </div>
                            </Motion.div>
                        )}
                    </Show>
                </Suspense>
            </main>
        </>
    );
}
