// apps/nextjs/components/layout/ClientLayout.tsx
'use client';

import { ThemeProvider } from '../providers/theme-provider';
import { AuthProvider } from '../../lib/auth-context';
import Navbar from '../navbar/Navbar';
import { Toaster } from 'sonner';

export function ClientLayout({ children }: { children: React.ReactNode }) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <AuthProvider>
        <Navbar />
        {children}
        <Toaster />
      </AuthProvider>
    </ThemeProvider>
  );
}

// apps/solidjs/src/components/layout/ClientLayout.tsx
import type { ParentProps } from "solid-js";
import { ThemeProvider } from "../providers/theme-provider";
import { AuthProvider } from "~/lib/auth-context";
import { Navbar } from "../navbar/Navbar";
import { Toaster } from "solid-toast";

export function ClientLayout(props: ParentProps) {
    return (
        <ThemeProvider>
            <AuthProvider>
                <Navbar />
                <main>{props.children}</main>
                <Toaster position="bottom-right" />
            </AuthProvider>
        </ThemeProvider>
    );
}
