// apps/solidjs/src/routes/register.tsx
import { Title } from "@solidjs/meta";
import { A, useNavigate } from "@solidjs/router";
import { createSignal, createEffect, Show } from "solid-js";
import { Motion } from "solid-motionone";
import { useAuth } from "~/lib/auth-context";

export default function RegisterPage() {
    const navigate = useNavigate();
    const { register, user, loading } = useAuth();

    const [formData, setFormData] = createSignal({
        name: "",
        email: "",
        password: "",
        confirmPassword: "",
    });
    const [error, setError] = createSignal("");
    const [isLoading, setIsLoading] = createSignal(false);

    // Redirect if already logged in
    createEffect(() => {
        if (user() && !loading()) {
            navigate("/dashboard");
        }
    });

    const handleChange = (e: Event) => {
        const target = e.target as HTMLInputElement;
        setFormData((prev) => ({
            ...prev,
            [target.name]: target.value,
        }));
        setError("");
    };

    const handleSubmit = async (e: Event) => {
        e.preventDefault();
        setError("");

        const data = formData();
        if (data.password !== data.confirmPassword) {
            setError("Passwords do not match");
            return;
        }

        if (data.password.length < 6) {
            setError("Password must be at least 6 characters");
            return;
        }

        setIsLoading(true);

        try {
            await register({
                name: data.name,
                email: data.email,
                password: data.password,
            });
            navigate("/dashboard");
        } catch (err) {
            setError(err instanceof Error ? err.message : "Registration failed. Please try again.");
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <>
            <Title>Register | Asepharyana</Title>
            <Show when={loading()}>
                <div class="min-h-screen flex items-center justify-center">
                    <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-primary" />
                </div>
            </Show>

            <Show when={!loading() && !user()}>
                <div class="min-h-screen flex items-center justify-center p-4 bg-gradient-to-br from-background via-background to-muted">
                    <Motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.5 }}
                        class="w-full max-w-md"
                    >
                        <div class="bg-card rounded-2xl shadow-2xl border border-border overflow-hidden">
                            <div class="p-8">
                                <div class="text-center mb-8">
                                    <h1 class="text-3xl font-bold bg-gradient-to-r from-primary to-purple-600 bg-clip-text text-transparent">
                                        Create Account
                                    </h1>
                                    <p class="text-muted-foreground mt-2">
                                        Sign up for a new account
                                    </p>
                                </div>

                                <Show when={error()}>
                                    <Motion.div
                                        initial={{ opacity: 0, x: -20 }}
                                        animate={{ opacity: 1, x: 0 }}
                                        class="mb-6 p-4 bg-destructive/10 border border-destructive/20 rounded-lg flex items-start gap-3"
                                    >
                                        <svg class="h-5 w-5 text-destructive mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <circle cx="12" cy="12" r="10" stroke-width="2" />
                                            <line x1="12" y1="8" x2="12" y2="12" stroke-width="2" />
                                            <circle cx="12" cy="16" r="1" fill="currentColor" />
                                        </svg>
                                        <p class="text-sm text-destructive">{error()}</p>
                                    </Motion.div>
                                </Show>

                                <form onSubmit={handleSubmit} class="space-y-4">
                                    <div class="space-y-2">
                                        <label for="name" class="text-sm font-medium text-foreground">Name</label>
                                        <input
                                            id="name"
                                            name="name"
                                            type="text"
                                            required
                                            value={formData().name}
                                            onInput={handleChange}
                                            class="w-full px-4 py-3 rounded-lg border border-input bg-background focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                                            placeholder="Your name"
                                            disabled={isLoading()}
                                        />
                                    </div>

                                    <div class="space-y-2">
                                        <label for="email" class="text-sm font-medium text-foreground">Email</label>
                                        <input
                                            id="email"
                                            name="email"
                                            type="email"
                                            required
                                            value={formData().email}
                                            onInput={handleChange}
                                            class="w-full px-4 py-3 rounded-lg border border-input bg-background focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                                            placeholder="your@email.com"
                                            disabled={isLoading()}
                                        />
                                    </div>

                                    <div class="space-y-2">
                                        <label for="password" class="text-sm font-medium text-foreground">Password</label>
                                        <input
                                            id="password"
                                            name="password"
                                            type="password"
                                            required
                                            value={formData().password}
                                            onInput={handleChange}
                                            class="w-full px-4 py-3 rounded-lg border border-input bg-background focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                                            placeholder="••••••••"
                                            disabled={isLoading()}
                                        />
                                    </div>

                                    <div class="space-y-2">
                                        <label for="confirmPassword" class="text-sm font-medium text-foreground">Confirm Password</label>
                                        <input
                                            id="confirmPassword"
                                            name="confirmPassword"
                                            type="password"
                                            required
                                            value={formData().confirmPassword}
                                            onInput={handleChange}
                                            class="w-full px-4 py-3 rounded-lg border border-input bg-background focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                                            placeholder="••••••••"
                                            disabled={isLoading()}
                                        />
                                    </div>

                                    <button
                                        type="submit"
                                        disabled={isLoading()}
                                        class="w-full py-3 text-base font-semibold rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-all disabled:opacity-50 flex items-center justify-center gap-2 mt-6"
                                    >
                                        {isLoading() ? "Creating account..." : (
                                            <>
                                                Create Account
                                                <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3" />
                                                </svg>
                                            </>
                                        )}
                                    </button>
                                </form>

                                <div class="mt-6 text-center">
                                    <p class="text-sm text-muted-foreground">
                                        Already have an account?{" "}
                                        <A href="/login" class="text-primary hover:underline font-semibold">
                                            Sign in
                                        </A>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </Motion.div>
                </div>
            </Show>
        </>
    );
}

// apps/NextJS/app/register/page.tsx
'use client';

import React, { useState, useRef, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { signIn } from 'next-auth/react';

function RegisterForm() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const errorRef = useRef<HTMLParagraphElement>(null);
  const router = useRouter();

  useEffect(() => {
    if (error && errorRef.current) {
      errorRef.current.focus();
    }
  }, [error]);

  const handleRegister = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError('');
    setIsSubmitting(true);

    try {
      // Step 1: Send data to the registration API
      const registerResponse = await fetch('/api/register', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name,
          email,
          password,
        }),
      });

      const registerData = await registerResponse.json();

      if (!registerResponse.ok) {
        setError(registerData.message || 'Registration failed. Please try again.');
        setIsSubmitting(false);
        return;
      }

      // Step 2: If registration is successful, try to sign in automatically
      const signInResponse = await signIn('credentials', {
        email,
        password,
        redirect: false, // Do not redirect automatically, we handle it manually
      });

      if (signInResponse?.error) {
        // If auto-login fails, inform the user to log in manually
        setError('Registration successful, but auto-login failed. Please log in from the login page.');
        // Redirect to the login page after a moment
        setTimeout(() => {
          router.push('/login');
        }, 3000);
      } else if (signInResponse?.ok) {
        // If auto-login is successful, redirect to the homepage
        router.push('/');
        router.refresh(); // Refresh the page to update session status
      }

    } catch (err) {
      setError('An error occurred. Please check your connection and try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <form onSubmit={handleRegister} className="space-y-4" role="form" aria-label="Register form">
      {error && (
        <p
          className="text-red-500 text-center bg-red-100 p-2 rounded-md"
          id="register-error"
          tabIndex={-1}
          ref={errorRef}
          aria-live="polite"
        >
          {error}
        </p>
      )}
      <div>
        <label htmlFor="name" className="block text-sm font-medium text-gray-700">Name</label>
        <input
          type="text"
          id="name"
          name="name"
          value={name}
          onChange={(e) => setName(e.target.value)}
          required
          aria-describedby={error ? 'register-error' : undefined}
          className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
        />
      </div>
      <div>
        <label htmlFor="email" className="block text-sm font-medium text-gray-700">Email</label>
        <input
          type="email"
          id="email"
          name="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          required
          aria-describedby={error ? 'register-error' : undefined}
          className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
        />
      </div>
      <div>
        <label htmlFor="password" className="block text-sm font-medium text-gray-700">Password</label>
        <input
          type="password"
          id="password"
          name="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
          minLength={6}
          aria-describedby={error ? 'register-error' : undefined}
          className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
        />
      </div>
      <button
        type="submit"
        disabled={isSubmitting}
        className='w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 disabled:bg-gray-400'
        aria-label="Register"
      >
        {isSubmitting ? 'Registering...' : 'Register'}
      </button>
      <div className="text-center mt-4">
        <Link href="/login" className="text-blue-600 hover:underline">
          Already have an account? Login here.
        </Link>
      </div>
    </form>
  );
}

export default function RegisterPage() {
  return (
    <div className='min-h-screen flex flex-col justify-center items-center'>
      <div className='p-10 rounded-lg shadow-lg'>
        <h1 className='mb-6 text-3xl font-bold text-center text-green-600'>
          Register
        </h1>
        <RegisterForm />
      </div>
    </div>
  );
}
