// apps/NextJS/app/(frontend)/(anime)/anime2/search/[slug]/page.tsx
'use client';
// app/search/[slug]/page.tsx
import SearchForm from '@/components/misc/SearchForm';
import CardA from '@/components/card/MediaCard';
import React, { useEffect, useState } from 'react';
import useSWR from 'swr';
import Loading from '@/components/misc/loading';
import { Search, Info } from 'lucide-react';
export const dynamic = 'force-dynamic';
interface Genre {
  name: string;
  slug: string;
  otakudesu_url: string;
}

interface Anime {
  title: string;
  slug: string;
  poster: string;
  description: string;
  anime_url: string;
  genres: Genre[];
  rating: string;
  type: string;
  season: string;
}

interface SearchDetailData {
  status: string;
  data: Anime[];
  pagination: {
    current_page: number;
    last_visible_page: number;
    has_next_page: boolean;
    next_page: string | null;
    has_previous_page: boolean;
    previous_page: string | null;
  };
}

const fetcher = (url: string) => fetch(url).then((res) => res.json());

const SearchPage = ({ params }: { params: Promise<{ slug: string }> }) => {
  const [resolvedParams, setResolvedParams] = useState<{ slug: string } | null>(
    null
  );

  useEffect(() => {
    params.then(setResolvedParams);
  }, [params]);

  const query = resolvedParams ? decodeURIComponent(resolvedParams.slug) : '';
  const { data: searchResults, error } = useSWR<SearchDetailData>(
    resolvedParams ? `/api/anime2/search?q=${encodeURIComponent(query)}` : null,
    fetcher,
    {
      revalidateIfStale: false,
      revalidateOnFocus: false,
      revalidateOnReconnect: false,
      dedupingInterval: 0,
      compare: (a, b) => JSON.stringify(a) === JSON.stringify(b), // Hindari infinite loop
    }
  );

  if (error) return <div>Error loading search results</div>;
  if (!searchResults) return <Loading />;

  return (
    <main className='min-h-screen p-6 bg-background dark:bg-dark'>
      <div className='max-w-7xl mx-auto space-y-8'>
        <div className='flex items-center gap-4'>
          <div className='p-3 bg-purple-100 dark:bg-purple-900/50 rounded-xl'>
            <Search className='w-8 h-8 text-purple-600 dark:text-purple-400' />
          </div>
          <h1 className='text-3xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent'>
            Search Results
          </h1>
        </div>

        <SearchForm classname='w-full' initialQuery={query} baseUrl='/anime' />

        {searchResults.data.length > 0 ? (
          <div className='grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4'>
            {searchResults.data.map((anime) => (
              <CardA
                key={anime.slug}
                title={anime.title}
                description={`⭐${anime.rating || 'N/A'}`}
                imageUrl={anime.poster}
                linkUrl={`/anime/detail/${anime.slug}`}
              />
            ))}
          </div>
        ) : (
          <div className='p-6 bg-blue-100 dark:bg-blue-900/30 rounded-2xl flex items-center gap-4'>
            <Info className='w-8 h-8 text-blue-600 dark:text-blue-400' />
            <h2 className='text-xl font-medium text-blue-800 dark:text-blue-200'>
              No results found for &quot;{query}&quot;
            </h2>
          </div>
        )}
      </div>
    </main>
  );
};

export default SearchPage;

// apps/solidjs/src/routes/anime/search/[slug].tsx
import { Title } from '@solidjs/meta';
import { A, useParams, useSearchParams } from '@solidjs/router';
import { createResource, For, Show, Suspense } from 'solid-js';
import { httpClient } from '~/lib/http-client';
import { CachedImage } from '~/components/CachedImage';

// Matches OpenAPI AnimeItem schema
interface AnimeItem {
  title: string;
  slug: string;
  poster: string;
  episode: string;
  anime_url: string;
  genres: string[];
  status: string;
  rating: string;
}

// Matches OpenAPI SearchResponse schema
interface SearchResponse {
  status: string;
  data: AnimeItem[];
  pagination: {
    current_page: number;
    last_visible_page: number;
    has_next_page: boolean;
    has_previous_page: boolean;
    next_page?: number | null;
    previous_page?: number | null;
  };
}

async function searchAnime(query: string): Promise<SearchResponse> {
  return httpClient.fetchJson<SearchResponse>(
    `/api/anime/search?q=${encodeURIComponent(query)}`,
  );
}

export default function AnimeSearchPage() {
  const params = useParams();
  const [searchParams] = useSearchParams();
  const query = (): string => params.slug || (searchParams.q as string) || '';

  const [data] = createResource(query, searchAnime);

  return (
    <>
      <Title>Search: {query()} | Anime | Asepharyana</Title>
      <main class="p-4 md:p-8 min-h-screen bg-background text-foreground">
        <div class="max-w-7xl mx-auto">
          <h1 class="text-3xl font-bold mb-2">Search Results</h1>
          <p class="text-muted-foreground mb-8">Results for "{query()}"</p>

          <Suspense
            fallback={
              <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
                <For each={Array(10).fill(0)}>
                  {() => (
                    <div class="aspect-[3/4] rounded-xl bg-muted animate-pulse" />
                  )}
                </For>
              </div>
            }
          >
            <Show when={data.error}>
              <div class="text-center py-12 text-destructive">
                Search failed
              </div>
            </Show>
            <Show when={data()}>
              {(searchData) => (
                <Show
                  when={searchData().data.length > 0}
                  fallback={
                    <div class="text-center py-12 text-muted-foreground">
                      No results found for "{query()}"
                    </div>
                  }
                >
                  <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
                    <For each={searchData().data}>
                      {(item) => (
                        <A
                          href={`/anime/detail/${item.slug}`}
                          class="group relative overflow-hidden rounded-xl bg-card border border-border hover:border-primary/50 transition-all"
                        >
                          <div class="aspect-[3/4] overflow-hidden">
                            <CachedImage
                              src={item.poster}
                              alt={item.title}
                              class="w-full h-full object-cover group-hover:scale-105 transition-transform"
                              fallbackClass="w-full h-full bg-muted animate-pulse"
                              loading="lazy"
                            />
                          </div>
                          <div class="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent" />
                          <div class="absolute bottom-0 left-0 right-0 p-3">
                            <h3 class="text-white text-sm font-medium line-clamp-2">
                              {item.title}
                            </h3>
                          </div>
                        </A>
                      )}
                    </For>
                  </div>
                </Show>
              )}
            </Show>
          </Suspense>
        </div>
      </main>
    </>
  );
}
